/* Production upload flow: compression, human-review gate, final result view, and persistence. */
(function () {
  'use strict';
  var input = document.getElementById('photoInput');
  var choose = document.getElementById('choose');
  var start = document.getElementById('start');
  var OriginalFileReader = window.FileReader;
  var OriginalFetch = window.fetch;
  var MAX_EDGE = 1800;
  var JPEG_QUALITY = 0.82;
  var MAX_TOTAL_BYTES = 10 * 1024 * 1024;
  var STATE_KEY = 'roadlens-analysis-flow-v2';
  var state = loadState();
  var pendingPayload = null;

  function openPicker(event) { if (event) { event.preventDefault(); event.stopPropagation(); } if (input) { input.removeAttribute('capture'); input.click(); } }
  if (choose) choose.addEventListener('click', openPicker, false);
  if (start) start.addEventListener('click', openPicker, false);
  if (input) input.addEventListener('click', function (event) { event.stopPropagation(); }, false);

  function compress(file) { return new Promise(function (resolve) { if (!file || !/^image\/(jpeg|png|webp)$/.test(file.type)) return resolve(file); var url = URL.createObjectURL(file), image = new Image(); image.onload = function () { var width = image.naturalWidth || image.width, height = image.naturalHeight || image.height, scale = Math.min(1, MAX_EDGE / Math.max(width, height)), canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(width * scale)); canvas.height = Math.max(1, Math.round(height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(url); canvas.toBlob(function (blob) { resolve(blob ? new File([blob], file.name.replace(/\.[^.]+$/, '.jpg'), { type: 'image/jpeg', lastModified: Date.now() }) : file); }, 'image/jpeg', JPEG_QUALITY); }; image.onerror = function () { URL.revokeObjectURL(url); resolve(file); }; image.src = url; }); }
  window.FileReader = function () { var reader = new OriginalFileReader(), originalRead = reader.readAsDataURL.bind(reader); reader.readAsDataURL = function (file) { compress(file).then(function (smaller) { originalRead(smaller); }); }; return reader; };
  window.FileReader.prototype = OriginalFileReader.prototype;

  function loadState() { try { var value = JSON.parse(localStorage.getItem(STATE_KEY) || '{}'); return value && typeof value === 'object' ? value : {}; } catch (_) { return {}; } }
  function saveState() { try { localStorage.setItem(STATE_KEY, JSON.stringify(state)); } catch (_) {} }
  function esc(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]); }); }
  function results() { return document.getElementById('results'); }
  function hideLegacyReport() { var report = document.getElementById('report'); if (report) report.classList.add('flow-hidden'); }
  function scrollResults() { var node = results(); if (node) node.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
  function reviewItems(report) { var list = []; (report.violations || []).forEach(function (violation, index) { (Array.isArray(violation.missing_evidence) ? violation.missing_evidence : []).filter(Boolean).forEach(function (label, itemIndex) { list.push({ id: index + '-' + itemIndex, index: index, label: String(label), violation: violation }); }); }); return list; }
  function statusLabel(status) { return status === 'confirmed' ? '確認違規' : status === 'excluded' ? '排除' : status === 'unknown' ? '無法確定' : '尚未確認'; }
  function hasReview(report) { return reviewItems(report).length > 0; }
  function ensureStyle() { if (document.getElementById('flowStyle')) return; var style = document.createElement('style'); style.id = 'flowStyle'; style.textContent = '.flow-hidden{display:none!important}.flow-page{display:grid;gap:18px}.flow-title{margin:0}.flow-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:18px}.flow-image-card,.flow-result-card,.flow-review-card{border:1px solid var(--line);border-radius:16px;padding:16px;background:var(--card)}.flow-images{display:grid;gap:12px}.flow-image{display:block;width:100%;max-height:520px;object-fit:contain;border-radius:12px;background:#edf2f7;cursor:zoom-in}.flow-evidence,.flow-meta{padding:12px;border-radius:10px;background:#f5f7fa;line-height:1.7;margin:10px 0}.flow-item{border:1px solid var(--line);border-left:4px solid var(--red);border-radius:12px;padding:14px;margin:10px 0}.flow-review-item{border-top:1px solid var(--line);padding:14px 0}.flow-review-options{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.flow-choice,.flow-actions button{min-height:44px;padding:10px 14px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--ink);font-weight:700}.flow-choice.selected{background:var(--blue);border-color:var(--blue);color:#fff;box-shadow:0 0 0 3px #1769e033}.flow-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.flow-stat{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.flow-stat div{padding:12px;border:1px solid var(--line);border-radius:10px;text-align:center}.flow-warning{color:var(--amber);font-weight:700}.flow-ok{color:#147d67;font-weight:700}@media(max-width:760px){.flow-grid{grid-template-columns:1fr}.flow-stat{grid-template-columns:1fr}.flow-review-options{display:grid;grid-template-columns:repeat(3,1fr)}.flow-choice{width:100%;padding:10px 4px}.flow-image{max-height:360px}}'; document.head.appendChild(style); }
  function imageMarkup() { var images = state.images || []; return images.length ? '<div class="flow-images">' + images.map(function (src, index) { return '<img class="flow-image" src="' + esc(src) + '" alt="本次分析原始圖片 ' + (index + 1) + '，點擊放大" data-flow-image>'; }).join('') + '</div>' : '<div class="flow-meta">本次分析未保存圖片預覽。</div>'; }
  function finalStatuses(report) { var items = reviewItems(report), map = {}; items.forEach(function (item) { map[item.index] = map[item.index] || []; map[item.index].push(state.reviews && state.reviews[item.id]); }); return (report.violations || []).map(function (violation, index) { var statuses = map[index] || []; if (!statuses.length) return { status: 'ai', label: 'AI 判定違規' }; if (statuses.indexOf('unknown') >= 0 || statuses.some(function (x) { return !x; })) return { status: 'unknown', label: '無法確定' }; if (statuses.every(function (x) { return x === 'excluded'; })) return { status: 'excluded', label: '排除' }; return { status: 'confirmed', label: '確認違規' }; }); }
  function fineSummary(report, statuses) { var confirmed = (report.violations || []).filter(function (_, index) { return statuses[index].status === 'confirmed' || statuses[index].status === 'ai'; }); var priced = confirmed.filter(function (v) { return Number(v.fine_min) > 0 && Number(v.fine_max) > 0; }); if (!priced.length) return '需查證'; var min = priced.reduce(function (sum, v) { return sum + Number(v.fine_min); }, 0), max = priced.reduce(function (sum, v) { return sum + Number(v.fine_max); }, 0); return 'NT$ ' + min.toLocaleString() + '～' + max.toLocaleString(); }
  function renderReview() { ensureStyle(); hideLegacyReport(); var report = state.report, items = reviewItems(report), node = results(); if (!node) return; node.innerHTML = '<div class="flow-page"><div><h2 class="flow-title">需要人工確認</h2><p class="sub">完成所有項目後才能查看最終分析結果。AI 判定與人工確認分開保存。</p></div><div class="flow-review-card">' + items.map(function (item) { var selected = state.reviews && state.reviews[item.id] || ''; return '<div class="flow-review-item" data-flow-review="' + esc(item.id) + '"><b>' + esc(item.label) + '</b><p class="sub">AI 判定：' + esc(item.violation.violation_type || item.violation.type || '疑似違規') + ' · AI 信心：' + esc(item.violation.confidence == null ? '未提供' : item.violation.confidence + '%') + '</p><div class="flow-review-options"><button class="flow-choice ' + (selected === 'confirmed' ? 'selected' : '') + '" data-flow-choice="confirmed">確認</button><button class="flow-choice ' + (selected === 'excluded' ? 'selected' : '') + '" data-flow-choice="excluded">不適用／不是違規</button><button class="flow-choice ' + (selected === 'unknown' ? 'selected' : '') + '" data-flow-choice="unknown">無法判斷</button></div><span class="flow-meta" data-flow-status>' + statusLabel(selected) + '</span></div>'; }).join('') + '<div class="flow-actions"><button class="btn primary" id="completeFlowReview">完成人工確認</button><button class="btn secondary" id="resetFlowReview">重設人工確認</button><span id="flowReviewMessage" role="status"></span></div></div></div>';
    node.querySelectorAll('[data-flow-choice]').forEach(function (button) { button.onclick = function () { var item = button.closest('[data-flow-review]'), id = item.getAttribute('data-flow-review'); state.reviews = state.reviews || {}; state.reviews[id] = button.getAttribute('data-flow-choice'); state.reviewCompleted = false; saveState(); item.querySelectorAll('.flow-choice').forEach(function (x) { x.classList.toggle('selected', x === button); }); item.querySelector('[data-flow-status]').textContent = statusLabel(state.reviews[id]); }; });
    document.getElementById('completeFlowReview').onclick = function () { var missing = items.filter(function (item) { return !state.reviews || !state.reviews[item.id]; }).length; if (missing) { document.getElementById('flowReviewMessage').textContent = '尚有 ' + missing + ' 項需要確認'; document.getElementById('flowReviewMessage').className = 'flow-warning'; return; } state.reviewCompleted = true; saveState(); renderFinal(); };
    document.getElementById('resetFlowReview').onclick = function () { state.reviews = {}; state.reviewCompleted = false; saveState(); renderReview(); };
  }
  function renderFinal() { ensureStyle(); hideLegacyReport(); var report = state.report, statuses = finalStatuses(report), confirmed = statuses.filter(function (x) { return x.status === 'confirmed'; }).length, excluded = statuses.filter(function (x) { return x.status === 'excluded'; }).length, unknown = statuses.filter(function (x) { return x.status === 'unknown'; }).length, noHuman = statuses.every(function (x) { return x.status === 'ai'; }); var node = results(); if (!node) return; node.innerHTML = '<div class="flow-page"><div class="result-head"><div><h2 class="flow-title">分析完成</h2><p class="sub">' + (noHuman ? 'AI 分析結果（不代表正式裁罰）' : '最終分析結果（包含使用者人工確認）') + '</p></div><span class="pill">' + (noHuman ? 'AI 分析結果' : '人工確認完成') + '</span></div><div class="flow-grid"><div class="flow-image-card"><h3>本次分析圖片</h3>' + imageMarkup() + '<p class="sub">圖片保持原始比例；未收到模型框選資料，因此不繪製額外框線。</p></div><div class="flow-result-card"><h3>最終判定</h3><div class="flow-stat">' + (noHuman ? '<div><b>AI 判定違規</b><br>' + statuses.length + ' 項</div>' : '<div><b>確認違規</b><br>' + confirmed + ' 項</div><div><b>排除</b><br>' + excluded + ' 項</div><div><b>無法確定</b><br>' + unknown + ' 項</div>') + '</div><div class="flow-meta"><b>預估罰款：</b>' + esc(fineSummary(report, statuses)) + '</div><p class="sub">這些數值是 AI 輔助分析資訊，不代表正式裁罰結果。</p></div></div><div class="flow-result-card"><h3>違規項目</h3>' + ((report.violations || []).map(function (v, index) { var s = statuses[index]; return '<article class="flow-item"><h4>' + esc(v.violation_type || v.type || '無法從此照片確認') + '</h4><div class="flow-meta"><b>AI 判定：</b>' + esc(v.violation_type || v.type || '未提供') + '<br><b>AI 信心度：</b>' + esc(v.confidence == null ? '未提供' : v.confidence + '%') + (s.status !== 'ai' ? '<br><b>人工確認：</b>' + esc(s.label) : '') + '<br><b>最終判定：</b>' + esc(s.status === 'ai' ? 'AI 判定違規' : s.label) + '</div><div class="flow-evidence"><b>圖片證據：</b>' + esc(v.evidence || v.evidence_location || '未提供') + '<br><b>判斷理由：</b>' + esc(v.reasoning || v.reason || '未提供') + (v.missing_evidence && v.missing_evidence.length ? '<br><b>不確定原因／需確認：</b>' + esc(v.missing_evidence.join('、')) : '') + '</div><b>預估罰款：</b>' + esc(s.status === 'excluded' || s.status === 'unknown' ? '不納入確定總額／需查證' : (v.fine_range || '需查證')) + '</article>'; }).join('') || '<p class="sub">無法從此照片確認違規項目。</p>') + '</div><div class="flow-result-card"><h3>分析摘要</h3><p>' + esc(report.summary || '未提供') + '</p></div><div class="flow-actions"><button class="btn primary" id="flowReanalyze">重新分析</button>' + (hasReview(report) ? '<button class="btn secondary" id="flowReReview">重新人工確認</button>' : '') + '<button class="btn secondary" id="flowHome">返回首頁</button></div></div>';
    node.querySelectorAll('[data-flow-image]').forEach(function (image) { image.onclick = function () { var win = window.open(); if (win) win.document.write('<img src="' + image.src + '" style="max-width:100%;height:auto">'); }; });
    document.getElementById('flowReanalyze').onclick = function () { state = {}; saveState(); var workspace = document.getElementById('workspace'); if (workspace) workspace.scrollIntoView({ behavior: 'smooth' }); window.location.reload(); };
    var reReview = document.getElementById('flowReReview'); if (reReview) reReview.onclick = function () { state.reviewCompleted = false; saveState(); renderReview(); };
    document.getElementById('flowHome').onclick = function () { window.scrollTo({ top: 0, behavior: 'smooth' }); };
  }
  function handleAnalysis(response) { response.clone().json().then(function (data) { if (!data || !Array.isArray(data.violations)) return; state.report = data; state.images = pendingPayload && pendingPayload.images ? pendingPayload.images : state.images || []; state.reviews = state.reviews || {}; saveState(); if (hasReview(data) && !state.reviewCompleted) renderReview(); else renderFinal(); }).catch(function () {}); }
  window.fetch = function (url, options) { if (String(url).indexOf('/api/analyze') !== -1 && options && typeof options.body === 'string') { try { var payload = JSON.parse(options.body); if (Array.isArray(payload.images) && payload.images.length) { delete payload.image; delete payload.mimeType; delete payload.mimeTypes; var total = payload.images.reduce(function (sum, value) { return sum + String(value).length; }, 0); if (total > MAX_TOTAL_BYTES * 1.4) return Promise.reject(new Error('圖片總大小超過上限，請減少照片或重新拍攝。')); pendingPayload = payload; options = Object.assign({}, options, { body: JSON.stringify(payload) }); } } catch (_) {} } var request = OriginalFetch.call(this, url, options); if (String(url).indexOf('/api/analyze') !== -1) request.then(handleAnalysis).catch(function () {}); return request; };
  if (state.report) { if (hasReview(state.report) && !state.reviewCompleted) renderReview(); else renderFinal(); }
})();
