export const ERROR_CODES = Object.freeze({
  IMAGE_INVALID: 'IMAGE_INVALID',
  IMAGE_TOO_LARGE: 'IMAGE_TOO_LARGE',
  IMAGE_LOW_QUALITY: 'IMAGE_LOW_QUALITY',
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  API_RATE_LIMIT: 'API_RATE_LIMIT',
  API_QUOTA: 'API_QUOTA',
  API_ERROR: 'API_ERROR',
  INVALID_AI_RESPONSE: 'INVALID_AI_RESPONSE',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
});

export function publicError(code, message) {
  return { code, message };
}
